language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  # Make sure there's only one swapper crate in scope
  - rm -rf target/debug/deps/*swapper*
  - cargo build -vv
  - cargo test
  - rustdoc --test README.md
